use_frameworks!

platform :ios, '10.0'

target 'CYSwiftKit_Example' do
  pod 'CYSwiftKit', :path => '../'

  target 'CYSwiftKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
